"""PR Feedback Sync — extract human feedback from Bitbucket PR comments.

Instead of asking reviewers to go to a separate dashboard to rate bug fixes,
we collect feedback directly on the PR where they're already reviewing code.

Flow:
1. Agent creates PR → posts a structured feedback template comment
2. Reviewer reviews code → fills in the template or writes a free-form comment
3. Sync endpoint reads PR comments → parses rating/feedback → updates experience

The feedback template uses a structured format that's easy for humans to fill
and easy for the parser to extract:

    ## Bug Fix Feedback
    **Rating:** ⭐⭐⭐⭐⭐ (1-5)
    **Difficulty:** L2
    **Comments:**
    > Your feedback here...

We also support free-form comments with embedded ratings like:
    "LGTM, 4 stars, nice fix but could add more tests"
"""
from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from typing import Optional

from app.backend.domains.bug_fix.bitbucket_client import (
    get_pr_comments,
    post_pr_comment,
    BitbucketMcpConfigError,
    BitbucketMcpToolError,
)
from app.backend.domains.bug_fix.experience_store import ExperienceStore

logger = logging.getLogger(__name__)

# ─── Feedback Template ────────────────────────────────────────────────────────

FEEDBACK_TEMPLATE = """\
## 🐛 Bug Fix Agent — Feedback Request

This PR was generated by the Bug Fix Agent. Please review and leave feedback below.

### How to give feedback

Reply to this comment with your rating and comments. You can use either format:

**Structured format:**
```
Rating: 4/5
Difficulty: L2
Comments: Good fix, but consider adding error handling for edge cases.
```

**Free-form format:**
Just write your thoughts naturally — e.g. "LGTM, 4 stars" or "Wrong approach, 2/5, should use try-with-resources instead of manual close"

### Rating Guide
| Stars | Meaning |
|-------|---------|
| ⭐⭐⭐⭐⭐ | Excellent — correct fix, clean code |
| ⭐⭐⭐⭐ | Good — correct but could be improved |
| ⭐⭐⭐ | Okay — right direction, poor execution |
| ⭐⭐ | Weak — partially correct, missed root cause |
| ⭐ | Wrong — incorrect fix or introduced regression |

### Difficulty Guide
| Level | Description |
|-------|-------------|
| L1 | Trivial — typo, missing import, simple null check |
| L2 | Easy — straightforward bug, clear fix pattern |
| L3 | Medium — requires understanding of system context |
| L4 | Hard — concurrency, distributed system, subtle race condition |

---
_Auto-generated by Bug Fix Agent · Experience ID: {experience_id}_
"""


# ─── Parsing ──────────────────────────────────────────────────────────────────

# Patterns to extract rating from comments
_RATING_PATTERNS = [
    # "Rating: 4/5" or "rating: 3 / 5"
    re.compile(r"rating\s*[:\-]\s*(\d)\s*/\s*5", re.IGNORECASE),
    # "4 stars" or "4星"
    re.compile(r"(\d)\s*(?:stars?|星|分)", re.IGNORECASE),
    # Star emojis: ⭐⭐⭐⭐ (count them)
    re.compile(r"(⭐{1,5})"),
    # "4/5" standalone
    re.compile(r"(\d)\s*/\s*5"),
]

_DIFFICULTY_PATTERN = re.compile(r"(?:difficulty|难度)\s*[:\-]?\s*(L[1-4])", re.IGNORECASE)

# Keywords that indicate this is a feedback comment (not a code review comment)
_FEEDBACK_SIGNALS = [
    "rating:", "stars", "星", "difficulty:", "难度:",
    "bug fix agent", "feedback", "评分", "评价",
]


def parse_rating(text: str) -> Optional[int]:
    """Extract a 1-5 rating from comment text."""
    for pattern in _RATING_PATTERNS:
        match = pattern.search(text)
        if match:
            value = match.group(1)
            if value.isdigit():
                rating = int(value)
                if 1 <= rating <= 5:
                    return rating
            elif "⭐" in value:
                rating = value.count("⭐")
                if 1 <= rating <= 5:
                    return rating
    return None


def parse_difficulty(text: str) -> str:
    """Extract difficulty level (L1-L4) from comment text."""
    match = _DIFFICULTY_PATTERN.search(text)
    return match.group(1).upper() if match else ""


def parse_feedback_text(text: str) -> str:
    """Extract the actual feedback content from a comment.

    Strips the rating/difficulty metadata and returns just the human's thoughts.
    """
    lines = text.strip().split("\n")
    feedback_lines = []

    for line in lines:
        stripped = line.strip()
        # Skip metadata lines
        if re.match(r"^(rating|difficulty|难度|stars?)\s*[:\-]", stripped, re.IGNORECASE):
            continue
        if re.match(r"^(#+\s|```|---|\|)", stripped):
            continue
        if stripped:
            feedback_lines.append(stripped)

    return "\n".join(feedback_lines).strip()


def is_feedback_comment(text: str) -> bool:
    """Check if a PR comment is likely a feedback response (not a code review comment)."""
    lower = text.lower()
    return any(signal in lower for signal in _FEEDBACK_SIGNALS)


# ─── Post Template ────────────────────────────────────────────────────────────

async def post_feedback_template(
    *,
    project: str,
    repo: str,
    pr_id: int,
    experience_id: int,
) -> bool:
    """Post the feedback template comment on a PR.

    Called after the PR is created, so the reviewer sees it when they open the PR.
    """
    try:
        comment_text = FEEDBACK_TEMPLATE.format(experience_id=experience_id)
        await post_pr_comment(
            project=project,
            repo=repo,
            pr_id=pr_id,
            text=comment_text,
        )
        logger.info(f"Posted feedback template on PR #{pr_id} in {project}/{repo}")
        return True
    except (BitbucketMcpConfigError, BitbucketMcpToolError) as e:
        logger.warning(f"Failed to post feedback template on PR #{pr_id}: {e}")
        return False


# ─── Sync ─────────────────────────────────────────────────────────────────────

async def sync_pr_feedback(
    *,
    project: str,
    repo: str,
    pr_id: int,
    experience_id: int,
    store: Optional[ExperienceStore] = None,
) -> dict:
    """Read PR comments, extract feedback, and update the experience.

    Returns a summary of what was synced.
    """
    if store is None:
        store = ExperienceStore()

    exp = store.get_by_id(experience_id)
    if not exp:
        return {"error": f"Experience #{experience_id} not found"}

    try:
        comments = await get_pr_comments(project=project, repo=repo, pr_id=pr_id)
    except (BitbucketMcpConfigError, BitbucketMcpToolError) as e:
        return {"error": f"Failed to fetch PR comments: {e}"}

    # Filter to feedback comments (skip the template we posted, skip code review comments)
    feedback_comments = []
    for c in comments:
        text = c.get("text", "")
        # Skip our own template comment
        if "Bug Fix Agent — Feedback Request" in text:
            continue
        # Skip bot comments
        if c.get("author", "").startswith("bot-"):
            continue
        # Check if it looks like feedback
        if is_feedback_comment(text) or parse_rating(text) is not None:
            feedback_comments.append(c)

    if not feedback_comments:
        return {
            "synced": False,
            "message": "No feedback comments found on this PR yet",
            "total_comments": len(comments),
        }

    # Use the most recent feedback comment
    latest = feedback_comments[-1]
    text = latest.get("text", "")
    author = latest.get("author_display") or latest.get("author", "unknown")

    rating = parse_rating(text)
    difficulty = parse_difficulty(text)
    feedback_text = parse_feedback_text(text)

    if not feedback_text and rating is None:
        return {
            "synced": False,
            "message": "Found comments but couldn't extract rating or feedback",
        }

    now = datetime.now(timezone.utc).isoformat()
    success = store.sync_pr_feedback(
        exp_id=experience_id,
        rating=rating,
        feedback=f"[PR #{pr_id} by {author}] {feedback_text}" if feedback_text else "",
        synced_at=now,
    )

    # Update difficulty if extracted
    if difficulty and success:
        store.update_experience(experience_id, {"difficulty_level": difficulty})

    return {
        "synced": success,
        "experience_id": experience_id,
        "rating": rating,
        "difficulty": difficulty,
        "feedback": feedback_text,
        "author": author,
        "pr_id": pr_id,
        "synced_at": now,
    }


async def sync_all_pending(store: Optional[ExperienceStore] = None) -> list[dict]:
    """Sync feedback for all experiences that have a PR but no rating yet."""
    if store is None:
        store = ExperienceStore()

    pending = store.get_unreviewed_with_pr()
    results = []

    for exp in pending:
        if not exp.pr_project or not exp.pr_repo or not exp.pr_id:
            continue
        result = await sync_pr_feedback(
            project=exp.pr_project,
            repo=exp.pr_repo,
            pr_id=exp.pr_id,
            experience_id=exp.id,
            store=store,
        )
        results.append({
            "experience_id": exp.id,
            "issue_key": exp.issue_key,
            **result,
        })

    return results
